import { Equipment } from "@/types/equipment";

export const mockEquipment: Equipment[] = [
  {
    id: "1",
    name: "Sony FX6",
    category: "cameras",
    brand: "Sony",
    model: "FX6",
    description: "Cámara de cine Full Frame 4K con capacidades profesionales",
    specs: [
      "Sensor Full Frame 10.2MP",
      "Grabación 4K 120fps",
      "Dual Base ISO",
      "15+ stops de rango dinámico",
    ],
    pricePerDay: 25000,
    pricePerWeek: 150000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800",
  },
  {
    id: "2",
    name: "Canon C70",
    category: "cameras",
    brand: "Canon",
    model: "C70",
    description: "Cámara compacta de cine 4K con montaje RF",
    specs: [
      "Sensor Super 35mm",
      "Grabación 4K 120fps",
      "16+ stops de rango dinámico",
      "Dual Gain Output",
    ],
    pricePerDay: 22000,
    pricePerWeek: 130000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800",
  },
  {
    id: "3",
    name: "ARRI SkyPanel S60-C",
    category: "lighting",
    brand: "ARRI",
    model: "SkyPanel S60-C",
    description: "Panel LED de color variable profesional",
    specs: [
      "Color variable RGB+W",
      "Control DMX/RDM",
      "300W de potencia",
      "Control remoto",
    ],
    pricePerDay: 15000,
    pricePerWeek: 90000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800",
  },
  {
    id: "4",
    name: "Sennheiser MKH 416",
    category: "audio",
    brand: "Sennheiser",
    model: "MKH 416",
    description: "Micrófono shotgun profesional estándar de la industria",
    specs: [
      "Patrón super-cardioide",
      "Rechazo lateral superior",
      "RF condenser",
      "Rango de frecuencia extendido",
    ],
    pricePerDay: 5000,
    pricePerWeek: 28000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800",
  },
  {
    id: "5",
    name: "DJI Ronin 2",
    category: "accessories",
    brand: "DJI",
    model: "Ronin 2",
    description: "Gimbal profesional de 3 ejes para cámaras pesadas",
    specs: [
      "Carga hasta 13.6kg",
      "Batería de 4 horas",
      "Modos múltiples de operación",
      "Control remoto",
    ],
    pricePerDay: 18000,
    pricePerWeek: 105000,
    status: "rented",
    imageUrl: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
  },
  {
    id: "6",
    name: "Canon EF 24-70mm f/2.8",
    category: "lenses",
    brand: "Canon",
    model: "EF 24-70mm f/2.8L II USM",
    description: "Lente zoom profesional versátil",
    specs: [
      "Apertura constante f/2.8",
      "Estabilización de imagen",
      "USM ultrasónico",
      "Sellado contra polvo y humedad",
    ],
    pricePerDay: 8000,
    pricePerWeek: 45000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1606244864456-8bee63fce472?w=800",
  },
  {
    id: "7",
    name: "Aputure 120D II",
    category: "lighting",
    brand: "Aputure",
    model: "120D Mark II",
    description: "Luz LED continua de alto rendimiento",
    specs: [
      "5500K temperatura de color",
      "150W de potencia",
      "CRI 96+",
      "Control inalámbrico",
    ],
    pricePerDay: 8500,
    pricePerWeek: 48000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800",
  },
  {
    id: "8",
    name: "Zoom F8n Pro",
    category: "audio",
    brand: "Zoom",
    model: "F8n Pro",
    description: "Grabadora multipista profesional de campo",
    specs: [
      "8 canales XLR",
      "32-bit float recording",
      "Timecode integrado",
      "Dual SD card slots",
    ],
    pricePerDay: 12000,
    pricePerWeek: 70000,
    status: "maintenance",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800",
  },
];

export const categoryNames: Record<string, string> = {
  cameras: "Cámaras",
  lenses: "Lentes",
  lighting: "Iluminación",
  audio: "Audio",
  accessories: "Accesorios",
  grip: "Grip",
};

export const statusNames: Record<string, string> = {
  available: "Disponible",
  rented: "Alquilado",
  maintenance: "Mantenimiento",
};

export const statusColors: Record<string, string> = {
  available: "bg-green-500",
  rented: "bg-primary",
  maintenance: "bg-yellow-500",
};
