-- Add new columns to spaces table for detailed rental space management
ALTER TABLE public.spaces 
ADD COLUMN IF NOT EXISTS hero_title text,
ADD COLUMN IF NOT EXISTS hero_subtitle text,
ADD COLUMN IF NOT EXISTS block_price integer DEFAULT 70000,
ADD COLUMN IF NOT EXISTS block_hours integer DEFAULT 4,
ADD COLUMN IF NOT EXISTS schedule_weekday text DEFAULT 'Lunes a viernes de 9 a 18 hs',
ADD COLUMN IF NOT EXISTS schedule_weekend text DEFAULT 'Fines de semana y fuera de horario a consultar',
ADD COLUMN IF NOT EXISTS discount_text text DEFAULT '20% de descuento en equipamiento adicional',
ADD COLUMN IF NOT EXISTS surface_area text,
ADD COLUMN IF NOT EXISTS features jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS included_items jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS optional_services jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS layout_description text,
ADD COLUMN IF NOT EXISTS location text DEFAULT 'Florida, Vicente López',
ADD COLUMN IF NOT EXISTS featured_image text,
ADD COLUMN IF NOT EXISTS tour_360_url text DEFAULT '/images/360-studio.jpg',
ADD COLUMN IF NOT EXISTS cta_text text DEFAULT 'Reservar Bloque';

-- Insert default data for Galería space
INSERT INTO public.spaces (
  name, 
  slug, 
  price, 
  status,
  hero_title,
  hero_subtitle,
  block_price,
  block_hours,
  schedule_weekday,
  schedule_weekend,
  discount_text,
  surface_area,
  features,
  included_items,
  optional_services,
  layout_description,
  location,
  description,
  detailed_description,
  cta_text
) VALUES (
  'Galería',
  'galeria',
  70000,
  'available',
  'ESTUDIO GALERÍA',
  'BLOQUES DE 4HS PARA TU PRODUCCIÓN AUDIOVISUAL',
  70000,
  4,
  'Lunes a viernes de 9 a 18 hs',
  'Fines de semana y fuera de horario a consultar',
  '20% de descuento en equipamiento adicional',
  '150 m²',
  '["Infinito blanco 6 m de ancho x 3 m de alto", "5 m de piso blanco", "11 m de tiro de cámara", "Altura 3 m", "Infinito negro incluido", "Chroma verde (3 x 6 m) incluido"]'::jsonb,
  '["3 fresneles 1K dimerizables", "16 tubos frontal/cenital", "2 x 4 tubos laterales", "Infinito blanco", "Infinito negro", "Chroma verde 3x6m"]'::jsonb,
  '["Tablero trifásico", "Back up de generador", "Pintura", "Streaming", "Podcast", "Equipamiento adicional"]'::jsonb,
  'El estudio cuenta con depósitos, montacargas, sala de locución, sala de edición/grabación, comedor y acceso vehicular.',
  'Florida, Vicente López',
  'Estudio de 150 m² con infinito blanco, negro y chroma verde incluidos.',
  'Espacio profesional de 150 m² totalmente equipado para producciones audiovisuales de alta calidad.',
  'RESERVAR BLOQUE'
);

-- Insert default data for Sala space
INSERT INTO public.spaces (
  name, 
  slug, 
  price, 
  status,
  hero_title,
  hero_subtitle,
  block_price,
  block_hours,
  schedule_weekday,
  schedule_weekend,
  discount_text,
  surface_area,
  features,
  included_items,
  optional_services,
  layout_description,
  location,
  description,
  detailed_description,
  cta_text
) VALUES (
  'Sala de Grabación / Postproducción',
  'sala-grabacion',
  70000,
  'available',
  'SALA DE GRABACIÓN',
  'POSTPRODUCCIÓN PROFESIONAL EN BLOQUES DE 4HS',
  70000,
  4,
  'Lunes a viernes de 9 a 18 hs',
  'Fines de semana y fuera de horario a consultar',
  '20% de descuento en equipamiento adicional',
  '40 m²',
  '["Tratamiento acústico profesional", "Iluminación controlada", "Climatización independiente", "Aislamiento sonoro"]'::jsonb,
  '["Consola de mezcla", "Monitores de estudio", "Micrófonos profesionales", "Interfaz de audio"]'::jsonb,
  '["Técnico de sonido", "Masterización", "Edición de video", "Streaming"]'::jsonb,
  'Sala de grabación y postproducción con tratamiento acústico profesional, ideal para locución, podcast y mezcla de audio.',
  'Florida, Vicente López',
  'Sala profesional para grabación de audio y postproducción.',
  'Espacio acústicamente tratado para grabación de locución, podcast, mezcla y postproducción de audio y video.',
  'RESERVAR BLOQUE'
);